# Generated by Django 5.1.1 on 2024-10-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_customuser_groups_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='policy_accept',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=1, verbose_name='Acepto las condiciones'),
        ),
    ]
