# Generated by Django 5.1.1 on 2024-10-02 16:17

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_customuser_country_customuser_policy_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
