# Generated by Django 5.1.1 on 2024-10-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_city_country_alter_customuser_document_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departament',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='departament',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='departament',
            new_name='department',
        ),
    ]
