# Generated by Django 5.1.1 on 2024-10-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_customuser_document_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
